name: Should be merged?

on:
  pull_request:
    branches:
      - main
      - "releases/**"
  schedule:
    - cron: "30 5,17 * * *"

jobs:
  validate-content:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm i --legacy-peer-deps

      - name: Format
        run: |
          npm run format

      - name: Lint
        run: |
          npm run lint
